apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hariharan346/D-Var.git'
    targetRevision: main
    path: Devops/exercise-3-argocd/manifests
    directory:
      exclude: 'application*.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    # AutoSync is disabled to allow us to simulate configuration drift
    # manually, creating OutOfSync states.
    automated: null
