apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment-dev
  labels:
    app: payment-service
    environment: dev
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: payment-service
  type: ClusterIP
