apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      serviceAccountName: app-sa
      containers:
      - name: app
        image: nginx