apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hariharan346/D-Var.git'
    targetRevision: HEAD
    path: Devops/ex-18/gitops/dev/payment-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: payment-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
